### ISSUE TITLE
JIS90 forms are unencoded and no way to switch to them easily

### ISSUE THREAD

**Issue by CoolMarvel43** [fontworks-fonts/Reggae#2]
_This issue applies to your following fonts: **DotGothic16**, **RocknRoll**, **Rampart**, **Reggae** (the one I am writing this issue on), **Stick** and **Klee**. Train has less Kanji (like only up to JIS Level 1 kanji), so it has JIS90 forms and hence this issue does not apply to Train._

The commercial version of your fonts follow the Adobe Japan 1-3 Std, and subsequently the JIS90 glyph standard. However, your open source version has JIS2004 glyph forms and no option (on my Mac, using advanced typography panel) to switch to JIS90 forms (which are subsequently unencoded (as shown by the text "Glyph 3,357")). In other words, the JIS90 forms are present in the open source version of the fonts, but they are very hard to find them. I don't know if this issue is a bug or not.

<img width="607" alt="Screenshot 2021-06-17 at 01 41 59" src="https://user-images.githubusercontent.com/10541683/122267340-5905aa00-cf0d-11eb-90c0-c4e6feebc6f2.png">

<img width="1022" alt="Screenshot 2021-06-17 at 01 39 36" src="https://user-images.githubusercontent.com/10541683/122266927-e85e8d80-cf0c-11eb-8c3d-74445c559dde.png">

_Above is your open source font, below is the commercial version of the font from your website to illustrate the glyph difference. My Mac's typography panel does not show "JIS1990 Forms" as well. Clicking on any of the options in the Character Shape does nothing to the glyphs._

If you intend to have JIS2004 forms, there should be extra kanji (some in CJK Compatibility Ideographs) to meet Adobe Japan 1-3 StdN requirements. Example given below is Toppan Bunkyu Midashi Mincho which is StdN compliant.

<img width="538" alt="Screenshot 2021-06-17 at 01 46 41" src="https://user-images.githubusercontent.com/10541683/122267808-e8ab5880-cf0d-11eb-9914-22a834b774b5.png">

However, I do not think this will happen as this means a lot of work designing new kanji (but then again, now anyone can do just that with Glyphs and make a pull request). So as of now, more urgently, please allow mapping to JIS90 forms.

**Comment by kokiabe** [comment]
@Marcus98T 
Font creators can map Unicode codepoints to either JIS90 or JIS2004 glyphs. They are also free to use 'jp90' or 'jp04' feature to implement the switching feature between JIS90 and JIS2004 glyphs. However, this font has a 'jp04' feature even though codepoints are mapped to JIS2004 glyphs. This is strange, so I removed its feature and implemented the 'jp90' feature instead.

Could you try from the [fix_jp90](https://github.com/fontworks-fonts/Reggae/tree/fix_jp90) branch and see if that fixes it? This opentype feature should allow you to switch to the JIS90 form! If it's OK, I'll expand it to other fonts.

Thanks!!

**Comment by CoolMarvel43** [comment]
The fix works. I can switch to the JIS90 forms as an option. Thank you so much, I hope to see the fix in your other fonts and in Google Fonts soon.
<img width="1054" alt="Screenshot 2021-06-21 at 18 08 12" src="https://user-images.githubusercontent.com/10541683/122745536-adb57600-d2bb-11eb-8d9b-546e3004f0e1.png">

**Comment by kokiabe** [comment]
@Marcus98T 
I've extended this fix to other fonts as well. I hope these fonts will be released soon on Goole Fonts!
