### ISSUE TITLE
Raggae One doesn't support Cyrillic characters?

### ISSUE THREAD

**Issue by utilmind** [fontworks-fonts/Reggae#3]
Hi! I found Reggae One on Google Fonts, https://fonts.google.com/specimen/Reggae+One, when looked for nice fonts that support Cyrillic characters. Looks like cyrillc works well on Google Fonts page, but I'm unable to get it working outside of Google, on my web-pages...

Here is the demo:
https://utilmind.com/demos/2021/unicode-range-test/

As you can see, Latin characters showing properly, Cyrillic is not. Is there something wrong with unicode-range of the font CSS?
I believe that Reggae One supports Cyrillic, but could you please give me any advice how to make it work?

**Comment by kokiabe** [comment]
@utilmind 
I read the [CSS](https://fonts.googleapis.com/css?family=Reggae+One), and it seems that Google Fonts uses the unicode-range property to subset fonts, and is designed to load only the minimum necessary chunks. Reggae One is a font with Cyrillic glyphs and codepoints, but the CSS provided by Google Fonts omits the Cyrillic range (U+0410 - U+044F) from the unicode-range of the <span>@</span>font-face specification, so Cyrillic characters cannot be displayed. The same applies to other Japanese fonts such as Noto Sans JP too.

**Comment by utilmind** [comment]
Thank you, @kokiabe!

I started using TTF directly, without Google Fonts. Downloaded TTF from this repository and uploaded to my demo site: http://utilmind/demos/2021/unicode-range-test/

Cyrillic characters seems having problems with kerning and require some tweaks, but anyway, much better than nothing! Wondering why Google advertised that this font supports Cyrillic, while it does not. But I'm still grateful to Google, because they let me find such nice font.

Thanks again, going to use TTFs directly.

**Comment by utilmind** [comment]
BTW, some language-specific Cyrillic characters seems missing. Ukrainian Іі, Її, Єє, Ґґ and Belarussian Ўў.

**Comment by kokiabe** [comment]
@utilmind 
This problem is not a bug, but is specific to Japanese fonts.

In countries and regions where Chinese characters, Kanji, are used, the concept of full-width and half-width characters exists. And many Japanese fonts contain full-width Cyrillic glyphs, because they are used in the Japanese language, not for Ukrainian, Russian, and other languages's notation. Of course, there is no rule that Cyrillic glyphs in Japanese fonts must be full-width, and there are exceptions such as MS Gothic.

Therefore, if you are writing in Cyrillic, it may be difficult to use. The reason for this problem is that alphabets and full-width alphabets are distinguished by Unicode codepoints, while Cyrillic is assigned only one codepoint without distinction.

**Comment by utilmind** [comment]
@kokiabe of course! I understand that Japanese and Chinese characters must have equal width. However this font already contains Latin characters with correct kerning, so I thought that Cyrillic could have nice looking kerning too.

I understand that it's not a bug, this font is not supposed to support Cyrillic texts. However, if you will ever have plans to improve it, then just make correct kerning. It's not feature request, just recommendation. I will think I will try to fix the width of characters myself in spare time, with Type light editor.
Thanks!

**Comment by kokiabe** [comment]
@utilmind
This font contains glyphs from the most common glyph sets for Japanese fonts, [Adobe-Japan1-3](https://github.com/adobe-type-tools/Adobe-Japan1), and the glyph set required for Google Fonts, [GF Latin Core](https://github.com/googlefonts/gftools/tree/main/Lib/gftools/encodings/GF%20Glyph%20Sets#gf-latin-core). As you said, this font don't fully support Ukrainian or Belarusian, nor have I no plans to add glyphs to this font. However, this font is licensed under the [SIL Open Font License](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL), you are free to add glyphs to them.

I'm sorry I couldn't help you...
