### ISSUE TITLE
Overly-tight kerning

### ISSUE THREAD

**Issue by aaronbell** [fontworks-fonts/Reggae#4]
In reviewing the kerning data, we found that there are some of the new kerning pairs that are super tight: 
![128333099-5090e375-a21f-4c2a-a6e2-fb9e3e560c88](https://user-images.githubusercontent.com/8460297/128743605-d9dbc5b5-b43a-4875-a43c-e4c7f4d8a643.gif)

Can you review the kerning data for the above pairs (and in general)?

**Comment by kokiabe** [comment]
@aaronbell   You’re right. So I reviewed and readjusted all the kerning pairs.
Could you try from the  [`adjust_kerning`](https://github.com/fontworks-fonts/Reggae/tree/adjust_kerning) branch and see if that fixes it?

**Comment by aaronbell** [comment]
@kokiabe Thanks for the update! These diagonals are notoriously challenging to get right. 

In reviewing, I still think it feels a bit tight. For example, compare the spacing from the middle of the `A` in `YARD` to the `Y` and `R` respectively (more on the right than left):
<img width="285" alt="Screen Shot 2021-08-19 at 9 14 12 AM" src="https://user-images.githubusercontent.com/8460297/130104579-ba4956f2-43ed-484e-9ad5-1693c1e8dae3.png">

Reducing the negative kern by 30-40 units between the `YA` and `LY` pairs is markedly better (and maybe even a little more?):
<img width="240" alt="Screen Shot 2021-08-19 at 9 15 19 AM" src="https://user-images.githubusercontent.com/8460297/130104771-23cc3f02-118e-4711-b331-7bad822e4bed.png">

Here's the full chart:
![kerns_new](https://user-images.githubusercontent.com/8460297/130104960-4df307e4-ce55-4fbd-90b7-5a7e3432fb36.gif)

**Comment by kokiabe** [comment]
@aaronbell   I readjusted all the kerning pairs.
Could you try from the  [`adjust_kerning`](https://github.com/fontworks-fonts/Reggae/tree/adjust_kerning) branch and see if that fixes it?

**Comment by aaronbell** [comment]
@kokiabe This is looking better. Thanks!!!
